micronaut:
  application:
    name: veiculoService
datasources:
  default:
    url: jdbc:postgresql://127.0.0.1:5432/dbveiculos
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 12345678
    schema-generate : CREATE_DROP
    dialect : POSTGRES
jpa:
  default:
    packages-to-scan:
      - 'br.com.francisco.model'
    properties:
      hibernate:
        hbm2ddl:
          auto : update
        show_sql : true
        format_sql : true